<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Formulaire</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
    <h1>Google Killer</h1>
    <p>Allez-y renseignez des urls pour qu'on crawl tout le web et qu'on détrone google !</p>
        <form method="post">
            <div><input type="text" name="url"></div>
            <div><input type="submit"></div>
        </form>
    </body>
</html>
